version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    expose:
      - 1883
    ports:
      - 1883:1883
      - 9001:9001
  
  pongdog_hw:
    image: matiah/pongdog-hw:latest
    network_mode: host
    volumes:
      - ./config:/pongdog_hw
    privileged: true
    depends_on:
      - mosquitto
    restart: unless-stopped
  
  pongdog_gamestate:
    image: matiah/pongdog-gamestate:latest
    network_mode: host
    volumes:
      - ./config:/pongdog_gamestate
    depends_on:
    - mosquitto
    - pongdog_hw
    restart: unless-stopped

  db:
    container_name: gamedb
    image: hypriot/rpi-mysql:latest
    ports:
        - "32001:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  app:
    container_name: pongdog_app
    image: jakvah/pongdog:raspibuild
    links:
        - "db"
    ports:
        - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped

