version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    expose:
      - 1883
    ports:
      - 1883:1883
      - 9001:9001
  
  hw:
    container_name: hw
    image: matiah/pongdog-hw:0.1
    network_mode: host
    volumes:
      - ./config.toml:/godog/config.toml
    privileged: true
    depends_on:
      - mosquitto
    restart: unless-stopped
  
  gamestate:
    container_name: gamestate
    image: matiah/pongdog-gamestate:no_conf
    network_mode: host
    volumes:
      - ./config.toml:/app/config.toml
    depends_on:
    - mosquitto
    - hw
    restart: unless-stopped

  db:
    container_name: gamedb
    image: hypriot/rpi-mysql:latest
    ports:
        - "32001:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  graphics:
    container_name: graphics
    image: jakvah/pongdog:0.1
    links:
        - "db"
    ports:
        - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped

