version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    expose:
      - 1883
    ports:
      - 1883:1883
      - 9001:9001
  
  pongdog_hw:
    image: matiah/pongdog-hw:testcandidate
    network_mode: host
    volumes:
      - ./config 
      - ./pongdog:/data
    privileged: true
    depends_on:
      - mosquitto
    restart: unless-stopped
  
  pongdog_gamestate:
    image: matiah/pongdog-gamestate:latest
    network_mode: host
    depends_on:
    - mosquitto
    - pongdog_hw
    restart: unless-stopped

  db:
    container_name: gamedb
    platform: linux/amd64
    image: mysql:5.7
    ports:
        - "32001:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root

  app:
    container_name: pongdog_app
    image: jakvah/pongdog:latest
    links:
        - "db"
    ports:
        - "5001:5000"
    depends_on:
    - db

